### PR TITLE
RHMAP-7734: convert to full cordova app

### PR DESCRIPTION
**Pull request by jcesarmobile**
Added config.xml with the default values and the plugins on www/config.json
Removed www/config.json
Linked cordova.js in the index.html
Added plugins and platforms folders to .gitignore

### CODE REVIEW

**Comment by corinnekrych** [comment]
+1 tested successfully in:
http://testing.client2.skunkhenry.com/#projects/rwerz7zebbj3djodzilxxato/apps/rwerz76ftf5cakchavq2ubib/editor

**Comment by wtrocki** [comment]
@jcesarmobile What cordova version is that using?  When cordova.js file should be added?

**Comment by jcesarmobile** [comment]
@wtrocki the platforms version is not set so it uses the fh-digger cordova-lib pinned versions. Currently cordova-lib is 6.3.1, cordova-ios is ~4.2.0 and cordova-android is ~5.2.0.

I don't think I understand the second question.
You don't have to add the actual cordova.js file anywhere, just link it in the index.html, it will be generated per platform on build time when fh-digger builds the app (or if you build it using Cordova CLI, the cordova.js will be in a copy of the www folder inside platforms/platformname folder when you add the platform 'platformname' )

**Comment by wtrocki** [comment]
@jcesarmobile thanks for response. 

ping @PhilipGough

**Pull request merged**
